"""empty message

Revision ID: 6b60e4bae3f4
Revises: 6bd3e2ecaf38
Create Date: 2018-11-01 22:48:18.825032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b60e4bae3f4'
down_revision = '6bd3e2ecaf38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_list', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_list')
    # ### end Alembic commands ###
